apiVersion: v1
data:
    config.yaml: |
        # use this file to override default configuration of `kuma-cp`
        #
        # see conf/kuma-cp.conf.yml for available settings
kind: ConfigMap
metadata:
    labels:
        app.kubernetes.io/instance: kuma
        app.kubernetes.io/name: kuma
    name: kuma-control-plane-config
    namespace: kuma-system
