apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    creationTimestamp: null
    name: meshes.kuma.io
spec:
    group: kuma.io
    names:
        kind: Mesh
        plural: meshes
    scope: Cluster
    versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
                description: Mesh is the Schema for the meshes API
                properties:
                    spec:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                type: object
          served: true
          storage: true
