apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    creationTimestamp: null
    name: zones.kuma.io
spec:
    group: kuma.io
    names:
        kind: Zone
        plural: zones
    scope: Cluster
    versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
                description: Zone is the Schema for the zone API
                properties:
                    mesh:
                        type: string
                    spec:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                type: object
          served: true
          storage: true
