apiVersion: v1
kind: Service
metadata:
  annotations:
    8080.service.kuma.io/protocol: http
    ingress.kubernetes.io/service-upstream: "true"
  labels:
    app: frontend
  name: frontend
  namespace: kuma-demo
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: frontend
